version: "3.7"

#networks:
#    internal-net:
#    external-net:    

services:
  db:
    image: mysql:8.0
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=app_db
      - MYSQL_USER=app_user
      - MYSQL_PASSWORD=app_pass
  api_app:
    image: php:apache
    volumes:
      - ./api/:/var/www/html:z
      - ./apache.conf:/etc/apache2/sites-enabled/000-default.conf
    depends_on:
      - db
    expose:
      - "80"     
#  fpm:
#    image: php:fpm
#    volumes:
#      - ./api/:/var/www/api
#    depends_on:
#      - db
#    expose:
#      - "9000"  
#  api_app:
#    image: nginx:latest
#    volumes:
#      - ./api/:/var/www/api
#      - ./nginx.conf:/etc/nginx/conf.d/default.conf
#    depends_on:
#      - db
#    expose:
#      - "7000"
  load_balancer:
    image: nginx:latest
    container_name: load_balancer
    volumes:
      - ./balancer.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api_app
    ports:
      - 8000:8000
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - cadvisor
  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    depends_on:
      - redis
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
  grafana:
    image: grafana/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=pass
    depends_on:
      - prometheus
    ports:
      - 3000:3000